"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "m5%-jr^27gr893xb%ey^%+2de#y844-oi5y1_!%h%^+1*bz5gj"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "192.168.1.245",
    "localhost",
]

DATA_UPLOAD_MAX_MEMORY_SIZE = 9242880

# Application definition

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"
INSTALLED_APPS = [
    "app",
    "baton",
    "modeltranslation",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.admindocs",
    "django_select2",
    "easy_thumbnails",
    "admin_auto_filters",
    "rangefilter",
    "import_export",
    "tinymce",
    "mptt",
    "news",
    "baton.autodiscover",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

help_modal = """
modalContent = `
    <div>
        <p><strong style="font-weight: 900">Welcome to django-baton!</strong></p>
        <p>This is ademo app which will try to introduce you django-baton and all its features. Baton is quite customizable, so
        here you'll see just one of the possible configurations, have a nice trip!</p>
        <p>
        BTW, this is an example of free menu voice, so you can customize the behaviour. In such case we're opening a modal using the <strong>Baton Modal utility</strong>. You can just define an url which points somewhere, you can alert stuff and so on...
        </p>
    </div>
`;
modal = new Baton.Modal({
    title: 'Help',
    content: modalContent,
});
modal.open();
"""


BATON = {
    "BATON_CLIENT_ID": os.getenv("BATON_CLIENT_ID"),
    "BATON_CLIENT_SECRET": os.getenv("BATON_CLIENT_SECRET"),
    "AI": {
        "ENABLE_TRANSLATIONS": True,
        "ENABLE_CORRECTIONS": True,
    },
    # "SITE_HEADER": "Baton Test App",
    # "SITE_TITLE": "Baton Test App",
    "INDEX_TITLE": "Baton administration",
    "SUPPORT_HREF": "mailto:mail@otto.to.it",
    "COPYRIGHT": 'copyright © 2024 <a href="https://www.otto.to.it">Otto srl</a>',  # noqa
    "POWERED_BY": "Otto srl",
    "CONFIRM_UNSAVED_CHANGES": False,
    "SHOW_MULTIPART_UPLOADING": True,
    "ENABLE_IMAGES_PREVIEW": True,
    "CHANGELIST_FILTERS_IN_MODAL": True,
    "CHANGELIST_FILTERS_ALWAYS_OPEN": False,
    "CHANGELIST_FILTERS_FORM": True,
    "CHANGEFORM_FIXED_SUBMIT_ROW": True,
    "COLLAPSABLE_USER_AREA": False,
    "MENU_ALWAYS_COLLAPSED": False,
    "MESSAGES_TOASTS": ["error"],
    "GRAVATAR_DEFAULT_IMG": "robohash",
    "GRAVATAR_ENABLED": True,
    "FORCE_THEME": None,
    "LOGIN_SPLASH": "/static/app/bg.jpg",
    "SEARCH_FIELD": {
        "label": "Search news",
        "url": "/admin/search/",
    },
    "MENU": (
        {
            "type": "title",
            "label": "System",
            "apps": ("auth",),
            "icon": "lock",
        },
        {
            "type": "app",
            "name": "auth",
            "label": "Authentication",
            "models": (
                {"name": "user", "label": "Users"},
                {"name": "group", "label": "Groups"},
            ),
        },
        {
            "type": "title",
            "label": "News",
            "apps": ("news",),
            "default_open": True,
            "icon": "breaking_news_alt_1",
            "children": [
                {
                    "type": "free",
                    "label": "Categories",
                    "url": "/admin/news/category/",
                    "re": "^/admin/news/category/(\d*)?",
                },
                {"type": "model", "label": "News", "name": "news", "app": "news"},
            ],
        },
        {
            "type": "title",
            "label": "Tools",
            "icon": "construction",
            "children": [
                {
                    "type": "free",
                    "label": "Password generator",
                    "url": "https://passwordsgenerator.net/",
                    "perms": ("auth.add_user", "auth.change_user"),
                },
                {
                    "type": "free",
                    "label": "Google search",
                    "url": "http://www.google.it",
                },
                {
                    "type": "free",
                    "url": "javascript:%s" % help_modal,
                    "label": "Help",
                },
            ],
        },
    ),
}

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True
LANGUAGE_CODE = "en-us"

MODELTRANSLATION_DEFAULT_LANGUAGE = "en"
LANGUAGES = (
    ("en", "ENG"),
    ("it", "ITA"),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = "/static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
