name: Type Check

on:
  push:
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Django mypy django-stubs requests
    - name: Run mypy
      run: PYTHONPATH=. mypy
