# Generated by Django 4.1.3 on 2022-11-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "draft"), (2, "published"), (3, "archived")],
                null=True,
            ),
        ),
    ]
