# Generated by Django 3.0.6 on 2020-05-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='datetime'),
        ),
    ]
