# Generated by Django 4.1.3 on 2022-11-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_news_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "draft"), (2, "reviewed"), (3, "ready"), (4, "archived")],
                null=True,
            ),
        ),
    ]
