# Generated by Django 3.0.6 on 2020-06-24 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('news', '0002_news_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_image', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(help_text='html is supported', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(blank=True, help_text='insert date', null=True, verbose_name='datetime'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='please insert a cool title', max_length=50, verbose_name='title'),
        ),
    ]
