# Generated by Django 3.0.6 on 2020-06-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200624_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
