# Generated by Django 5.1.3 on 2024-12-02 08:49

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_news_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="attachments_summary_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="attachments summary"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="attachments_summary_it",
            field=models.TextField(
                blank=True, null=True, verbose_name="attachments summary"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="content_en",
            field=tinymce.models.HTMLField(
                help_text="html is supported", null=True, verbose_name="content"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="content_it",
            field=tinymce.models.HTMLField(
                help_text="html is supported", null=True, verbose_name="content"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="title_en",
            field=models.CharField(
                help_text="please insert a cool title",
                max_length=50,
                null=True,
                verbose_name="title",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="title_it",
            field=models.CharField(
                help_text="please insert a cool title",
                max_length=50,
                null=True,
                verbose_name="title",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="videos_summary_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="videos summary"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="videos_summary_it",
            field=models.TextField(
                blank=True, null=True, verbose_name="videos summary"
            ),
        ),
    ]
