# Generated by Django 5.1.3 on 2024-12-02 12:41

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_news_attachments_summary_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="summary",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="summary"
            ),
        ),
    ]
