# Generated by Django 5.1.3 on 2024-12-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_news_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image_alt",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="image alt"
            ),
        ),
    ]
