# Generated by Django 5.1.3 on 2024-12-11 09:46

import baton.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_news_image_alt"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image_subject_location",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                verbose_name="image subject location",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=baton.fields.BatonAiImageField(
                alt_field="image_alt",
                blank=True,
                null=True,
                subject_location_field="image_subject_location",
                upload_to="news/img",
            ),
        ),
    ]
