# Generated by Django 5.1.3 on 2024-12-11 10:48

import baton.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_news_image_subject_location_alter_news_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="image",
            field=baton.fields.BatonAiImageField(
                alt_chars=20,
                alt_field="image_alt",
                alt_language="en-us",
                blank=True,
                null=True,
                subject_location_field="image_subject_location",
                upload_to="activity/img",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="image_alt",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="image alt"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="image_subject_location",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                verbose_name="image subject location",
            ),
        ),
    ]
