# Generated by Django 5.2.1 on 2026-06-05 16:02

import editor_js.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_activity_image_activity_image_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='body',
            field=editor_js.fields.EditorJSField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='news',
            name='body_en',
            field=editor_js.fields.EditorJSField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='news',
            name='body_it',
            field=editor_js.fields.EditorJSField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='news',
            name='body_summary',
            field=editor_js.fields.EditorJSField(blank=True, null=True, verbose_name='body summary'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image_subject_location',
            field=models.CharField(blank=True, default='50,50', max_length=7, null=True, verbose_name='image subject location'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_subject_location',
            field=models.CharField(blank=True, default='50,50', max_length=7, null=True, verbose_name='image subject location'),
        ),
    ]
